account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_view
from django.urls import path

app_name = 'account'

urlpatterns = [
    #url(r'^login/$', views.user_login, name='login'),
    url(r'^login/$', auth_view.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_view.LogoutView.as_view(), name='logout'),    
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^password_change/$', auth_view.PasswordChangeView.as_view(), 
    {'post_change_redirect' : 'account:password_change_done'}, name='password_change'),
    url(r'^password_change/done/$', auth_view.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password-reset/$', auth_view.PasswordResetView.as_view(), {'post_reset_redirect':'account:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done/$', auth_view.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_view.PasswordResetConfirmView.as_view(), {'post_reset_redirect':'account:password_reset_complete'} ,name='password_reset_confirm'),
    url(r'^password-reset/complete/$', auth_view.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
    
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

images/urls.py
from django.conf.urls import url
from . import views

app_name='images'

urlpatterns = [
    url('^$', views.image_list, name='list'),
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
]

account/models.py
from django.db import models
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return "Profiel for user {}".format(self.user.username)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from account.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()   # username
    password = forms.CharField(widget=forms.PasswordInput)  # password


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='password',
                                widget=forms.PasswordInput)
    password_1 = forms.CharField(label='Repeat password',
                                    widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password_1(self):
        """clean_<field> is used to test user/.
        check user input against our rules."""

        user_data = self.cleaned_data  # obtain user inputed data
        if user_data['password'] != user_data['password_1']:
            raise forms.ValidationError('Passwords don\'t match.')
        
        # return field we are checking
        return user_data['password_1']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from account.models import Profile
from django.contrib import messages



def user_login(request):
    
    if request.method == "POST":
        form = LoginForm(data=request.POST)  # prepopulate form with data.

        if form.is_valid():
            cd = form.cleaned_data

            # authenticate users against the database
            user = authenticate(request, username=cd['username'], password=cd['password'])
            # returns user or None

            if user is not None:
                if user.is_active:
                    # login user into the current session
                    login(request, user)
                    return HttpResponse("User has logged in. Authenticated Successfully")

                else:
                    return HttpResponse("Your account is no more active. it has being blocked.")

            else:
                return HttpResponse("Username or Password is not correct.")    

    else:
        form = LoginForm()

    return render(request,
                    'account/login.html',
                    {'form':form})
        
@login_required
def dashboard(request):
    return render(request,
                 'account/dashboard.html',
                 {'section':'dashboard'})

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)

        if form.is_valid():
            cd = form.cleaned_data  # obtain user's data
            # create new user's instance but don't save to the database yet.
            new_user = form.save(commit=False)
            new_user.set_password(cd['password'])
            # create a new profile for a new user
            Profile.objects.create(user=new_user)
            new_user.save()
            return render(request,
                            'account/register_done.html',
                            {'new_user':new_user})
    else:
        form = UserRegistrationForm()  # empty form of user.

    return render(request,
                    'account/register.html',
                    {'form':form})

@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEditForm(data=request.POST,
                                    instance=request.user)
        profile_form = ProfileEditForm(data=request.POST,
                                    instance=request.user.profile,
                                    files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            messages.success(request, 'Profile Updated successfully.')

        else:
            messages.error(request, "Error updating your profile.")

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request,
                'account/edit.html',
                {'profile_form':profile_form,
                'user_form':user_form})

account/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>

    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel='stylesheet' href='{% static "css/base.css" %}'>
    </head>
    <body>
        <div id='header'>
            <span class='logo'>Bookmarks</span>
            {% if request.user.is_authenticated %}
                <ul class='menu'>
                    <li {% if section == "dashboard" %}class='selected'{% endif %}>
                        <a href='{% url "account:dashboard" %}'>
                            dashboard
                        </a>
                    </li>
                    <li {% if section == "images" %}class='selected'{% endif %}>
                        <a href='{% url "images:list" %}'>
                            Images
                        </a>
                    </li>
                    <li {% if section == "people" %}class='selected'{% endif %}>
                        <a href='#'>
                            People
                        </a>
                    </li>
                </ul>
            {% endif %}

            <span class='user'>
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name }}
                    <a href='{% url "account:logout" %}'>logout</a>
                {% else %}
                    <a href='{% url "account:login" %}'>login</a>
                {% endif %}
            </span>
        </div>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }}
                        <a href="#" class="close">✖</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        <div id='content'>
            {% block content %}
            {% endblock %}
        </div>

    <script src='{% static "js/jquery.js" %}'></script>
    <script src='{% static "js/jquery.cookie.js" %}'></script>
    <script>
     //csrf_token setup for ajax
         var csrftoken = $.cookie('csrftoken');
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
        $.ajaxSetup({
             beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                 xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
         }
        });

        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
        });
    </script>

    </body>

</html>